### ISSUE TITLE
Using this crate with ublox over I2C/UART on embedded

### ISSUE THREAD

**Issue by gauteh** [ublox-rs/ublox#80]
Hi, I think this looks like a very useful project,

Can I use this crate to talk to a ublox device over I2C or UART on an embedded system? Should I write some driver that pushes things back and forth over I2C? Do you have any examples on that?

https://github.com/gauteh/sfy/issues/170

Cheers, Gaute

**Comment by gwbres** [comment]
Hello,

I personaly have used UART on embedded platforms before. You can follow the [provided example for that](https://github.com/ublox-rs/ublox/blob/master/examples/ublox-cli/src/main.rs#L316), but have never tested other communication buses

**Comment by gauteh** [comment]
Thank you.
